// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Proje_Web.Models;

#nullable disable

namespace Proje_Web.Migrations
{
    [DbContext(typeof(UyeContext))]
    [Migration("20251217162147_antrenor_degisiklik")]
    partial class antrenor_degisiklik
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Proje_Web.Models.Antrenor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Uzmanlik_alani")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("hizmet_turleri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("musaitlik_saatleri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Antrenor_Tablo");
                });

            modelBuilder.Entity("Proje_Web.Models.HizmetTurleri", b =>
                {
                    b.Property<string>("Hizmet_turu")
                        .HasColumnType("text");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("numeric");

                    b.Property<string>("sure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Hizmet_turu");

                    b.ToTable("Hizmet_Turleri_Tablosu");
                });

            modelBuilder.Entity("Proje_Web.Models.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Egitmen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HizmetAy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HizmetTuru")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HizmetUcret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RandevuTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Randevu_tablosu");
                });

            modelBuilder.Entity("Proje_Web.Models.Uye", b =>
                {
                    b.Property<string>("ad")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("parola")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("ad");

                    b.ToTable("Uye_Tablo");
                });
#pragma warning restore 612, 618
        }
    }
}
