// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Proje_Web.Models;

#nullable disable

namespace Proje_Web.Migrations
{
    [DbContext(typeof(UyeContext))]
    partial class UyeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Proje_Web.Models.Uye", b =>
                {
                    b.Property<string>("ad")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("parola")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("ad");

                    b.ToTable("Uye_Tablo");
                });
#pragma warning restore 612, 618
        }
    }
}
